# Generated by Django 5.1.4 on 2026-08-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribunals', '0048_ingestionrun_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=16)),
                ('chave', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('rotulo', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Coletada'), ('vazia', 'Vazia'), ('inexistente', 'Inexistente'), ('falha', 'Falha'), ('fora_janela', 'Fora da janela'), ('sem_aproveit', 'Sem dado aproveitável')], default='pendente', max_length=16)),
                ('itens_esperados', models.IntegerField(blank=True, null=True)),
                ('itens_gravados', models.IntegerField(default=0)),
                ('itens_duplicados', models.IntegerField(default=0)),
                ('bytes_baixados', models.BigIntegerField(default=0)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('coletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edicoes', to='tribunals.ingestionrun')),
                ('tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edicoes_diario', to='tribunals.tribunal')),
            ],
            options={
                'ordering': ['-data', 'chave'],
                'indexes': [models.Index(fields=['fonte', 'status', 'data'], name='diarios_edi_fonte_32bf04_idx'), models.Index(fields=['fonte', '-data'], name='diarios_edi_fonte_226e03_idx'), models.Index(fields=['tribunal', '-data'], name='diarios_edi_tribuna_7b65ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('fonte', 'chave'), name='uniq_edicao_fonte_chave')],
            },
        ),
    ]
