# Generated by Django 5.1.4 on 2026-08-17 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_showcaseanalise_facetas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('descoberta', 'Descoberta'), ('feature', 'Entrega'), ('incidente', 'Incidente'), ('decisao', 'Decisão'), ('medicao', 'Medição')], default='descoberta', max_length=16)),
                ('impacto', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], default='medio', max_length=8)),
                ('resumo', models.CharField(max_length=400)),
                ('corpo', models.TextField(blank=True, default='')),
                ('numeros', models.JSONField(blank=True, default=list)),
                ('referencias', models.JSONField(blank=True, default=list)),
                ('area', models.CharField(blank=True, default='', max_length=60)),
                ('data_evento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nota de acompanhamento',
                'verbose_name_plural': 'notas de acompanhamento',
                'ordering': ['-data_evento', '-criado_em'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='dashboard_c_session_6c64e8_idx',
            old_name='dash_chatmsg_sess_id_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='dashboard_c_user_id_af4069_idx',
            old_name='dash_chatsess_user_last_idx',
        ),
        migrations.AddField(
            model_name='notaacompanhamento',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_acompanhamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notaacompanhamento',
            index=models.Index(fields=['-data_evento'], name='dashboard_n_data_ev_ab6032_idx'),
        ),
        migrations.AddIndex(
            model_name='notaacompanhamento',
            index=models.Index(fields=['tipo', '-data_evento'], name='dashboard_n_tipo_41ef11_idx'),
        ),
    ]
