# Generated by Django 5.1.4 on 2026-04-26 23:59

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=accounts.models._gerar_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models._expiracao_default)),
                ('email_hint', models.EmailField(blank=True, max_length=254)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('used_user_agent', models.CharField(blank=True, max_length=500)),
                ('used_ip_country', models.CharField(blank=True, max_length=80)),
                ('used_ip_country_code', models.CharField(blank=True, max_length=4)),
                ('used_ip_region', models.CharField(blank=True, max_length=80)),
                ('used_ip_city', models.CharField(blank=True, max_length=120)),
                ('used_ip_isp', models.CharField(blank=True, max_length=180)),
                ('used_ip_org', models.CharField(blank=True, max_length=180)),
                ('used_ip_asn', models.CharField(blank=True, max_length=80)),
                ('used_ip_mobile', models.BooleanField(blank=True, null=True)),
                ('used_ip_hosting', models.BooleanField(blank=True, null=True)),
                ('used_ip_proxy', models.BooleanField(blank=True, null=True)),
                ('used_ip_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_in_token_40ea29_idx'), models.Index(fields=['used_at'], name='accounts_in_used_at_30e299_idx')],
            },
        ),
    ]
