# Generated by Django 5.1.4 on 2026-08-02 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribunals', '0044_seed_fonte_diario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('oab', models.CharField(blank=True, max_length=20)),
                ('tribunais', models.JSONField(default=list)),
                ('is_monitored_diario', models.BooleanField(default=True)),
                ('is_monitored_tribunal', models.BooleanField(default=False)),
                ('is_advogado', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnj', models.CharField(max_length=25)),
                ('tribunais', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=1024)),
                ('source_ids', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reviewed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2500)),
                ('secret', models.CharField(max_length=64)),
                ('evento_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='tribunals.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('term', 'Termo'), ('person', 'Pessoa'), ('proc', 'Processo')], max_length=10)),
                ('target_id', models.BigIntegerField()),
                ('snippet', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('erro_entrega', models.TextField(blank=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='tribunals.movimentacao')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-detected_at'], name='monitoring__target__bb0ff2_idx'), models.Index(fields=['-detected_at'], name='monitoring__detecte_a59503_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id', 'movimentacao'), name='uniq_detection')],
            },
        ),
    ]
