# Generated by Django 5.1.4 on 2026-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribunals', '0048_ingestionrun_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=16)),
                ('external_id', models.CharField(max_length=120)),
                ('esfera', models.CharField(choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('federal', 'Federal')], max_length=12)),
                ('ente', models.CharField(max_length=160)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('territory_id', models.CharField(blank=True, max_length=7)),
                ('data_publicacao', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('orgao', models.CharField(blank=True, max_length=255)),
                ('tipo_documento', models.CharField(blank=True, max_length=120)),
                ('edicao', models.CharField(blank=True, max_length=40)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('link_texto', models.URLField(blank=True, max_length=500)),
                ('texto', models.TextField()),
                ('texto_integral_chars', models.IntegerField(default=0)),
                ('texto_completo', models.BooleanField(default=False)),
                ('consultas', models.JSONField(blank=True, default=list)),
                ('confianca', models.CharField(choices=[('alta', 'Alta (frase)'), ('baixa', 'Baixa (termo)')], default='baixa', max_length=8)),
                ('cnjs', models.JSONField(blank=True, default=list)),
                ('cpfs_no_texto', models.PositiveIntegerField(default=0)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('processos', models.ManyToManyField(blank=True, related_name='publicacoes_oficiais', to='tribunals.process')),
            ],
            options={
                'verbose_name': 'Publicação oficial de ente',
                'verbose_name_plural': 'Publicações oficiais de entes',
                'ordering': ['-data_publicacao', 'ente'],
                'indexes': [models.Index(fields=['fonte', '-data_publicacao'], name='diarios_ent_fonte_a22811_idx'), models.Index(fields=['territory_id', '-data_publicacao'], name='diarios_ent_territo_d9c1a9_idx'), models.Index(fields=['uf', '-data_publicacao'], name='diarios_ent_uf_549901_idx'), models.Index(fields=['confianca', '-data_publicacao'], name='diarios_ent_confian_8e5664_idx')],
                'constraints': [models.UniqueConstraint(fields=('fonte', 'external_id'), name='uniq_pubof_fonte_extid')],
            },
        ),
    ]
