# Generated by Django 5.1.4 on 2026-04-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0008_process_ano_cnj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('total_processos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ClasseJudicial',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('total_processos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RenameIndex(
            model_name='ingestionrun',
            new_name='tribunals_i_tribuna_8eaa80_idx',
            old_name='run_trib_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='ingestionrun',
            new_name='tribunals_i_status_1aec87_idx',
            old_name='run_status_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='ingestionrun',
            new_name='tribunals_i_tribuna_e56d8b_idx',
            old_name='run_trib_window_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='tribunals_m_process_d27e25_idx',
            old_name='mov_proc_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='tribunals_m_tribuna_0443dc_idx',
            old_name='mov_trib_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='tribunals_m_inserid_c66809_idx',
            old_name='mov_inserido_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='tribunals_m_tribuna_7cd20d_idx',
            old_name='mov_trib_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='tribunals_m_hash_c1d24b_idx',
            old_name='mov_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='parte',
            new_name='tribunals_p_nome_b93914_idx',
            old_name='parte_nome_idx',
        ),
        migrations.RenameIndex(
            model_name='parte',
            new_name='tribunals_p_documen_148c2a_idx',
            old_name='parte_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='parte',
            new_name='tribunals_p_oab_a1f8d7_idx',
            old_name='parte_oab_idx',
        ),
        migrations.RenameIndex(
            model_name='parte',
            new_name='tribunals_p_tipo_00e582_idx',
            old_name='parte_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_tribuna_6983dd_idx',
            old_name='tribunals_p_tribuna_cnj_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_tribuna_4aae17_idx',
            old_name='tribunals_p_ult_mov_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_inserid_2f1d79_idx',
            old_name='tribunals_p_inserido_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_enrique_dfe240_idx',
            old_name='proc_enriqu_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_enrique_169bf9_idx',
            old_name='proc_enriq_status_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_classe__9f5d96_idx',
            old_name='proc_classe_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_orgao_j_f2e059_idx',
            old_name='proc_orgao_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_ano_cnj_363cc4_idx',
            old_name='proc_ano_cnj_idx',
        ),
        migrations.RenameIndex(
            model_name='process',
            new_name='tribunals_p_tribuna_cb5298_idx',
            old_name='proc_trib_ano_idx',
        ),
        migrations.RenameIndex(
            model_name='processoparte',
            new_name='tribunals_p_parte_i_31a1d2_idx',
            old_name='pp_parte_polo_idx',
        ),
        migrations.RenameIndex(
            model_name='processoparte',
            new_name='tribunals_p_process_8ffa81_idx',
            old_name='pp_proc_polo_idx',
        ),
        migrations.RenameIndex(
            model_name='processoparte',
            new_name='tribunals_p_papel_68db00_idx',
            old_name='pp_papel_idx',
        ),
        migrations.RenameIndex(
            model_name='schemadriftalert',
            new_name='tribunals_s_resolvi_2df766_idx',
            old_name='drift_resolv_trib_idx',
        ),
        migrations.AlterField(
            model_name='ingestionrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processoparte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schemadriftalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='assunto',
            index=models.Index(fields=['nome'], name='tribunals_a_nome_c315f4_idx'),
        ),
        migrations.AddField(
            model_name='process',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='tribunals.assunto'),
        ),
        migrations.AddIndex(
            model_name='classejudicial',
            index=models.Index(fields=['nome'], name='tribunals_c_nome_088c7e_idx'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='tribunals.classejudicial'),
        ),
        migrations.AddField(
            model_name='process',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='tribunals.classejudicial'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['classe'], name='tribunals_m_classe__1df891_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['classe'], name='tribunals_p_classe__05f562_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['assunto'], name='tribunals_p_assunto_da9b3f_idx'),
        ),
    ]
