# Generated by Django 5.1.4 on 2026-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0010_populate_classe_assunto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parte',
            name='uniq_parte_documento',
        ),
        migrations.AddConstraint(
            model_name='parte',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('documento', ''), _negated=True), models.Q(('documento__contains', 'X'), _negated=True), models.Q(('documento__contains', 'x'), _negated=True), models.Q(('documento__contains', '*'), _negated=True)), fields=('documento',), name='uniq_parte_documento_real'),
        ),
        migrations.AddConstraint(
            model_name='parte',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__contains', 'X'), ('documento__contains', 'x'), ('documento__contains', '*'), _connector='OR'), fields=('nome', 'documento'), name='uniq_parte_documento_mascarado'),
        ),
    ]
