# Generated by Django 5.1.4 on 2026-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0013_parte_sem_doc_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='enriquecimento_tentativas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
