# Generated by Django 5.1.4 on 2026-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0014_parte_tentativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
