# Generated by Django 5.1.4 on 2026-04-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0015_mov_data_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='ultima_sinc_djen_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
