# Generated by Django 5.1.4 on 2026-05-11 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0023_proc_ultmov_classif_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classificadorversao',
            name='shadow',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AmostraProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('score_no_sorteio', models.FloatField()),
                ('classificacao_no_sorteio', models.CharField(max_length=20)),
                ('suspeita_score', models.FloatField(blank=True, null=True)),
                ('motivos_suspeita', models.JSONField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amostra_itens', to='tribunals.process')),
            ],
            options={
                'verbose_name': 'item de amostra',
                'verbose_name_plural': 'itens de amostra',
                'ordering': ['amostra', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='AmostraValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('top_score', 'Top score (≥ 0.7)'), ('borderline', 'Borderline (0.30-0.70)'), ('low_score', 'Low score (0.05-0.30)'), ('falsos_consumidos', 'Falsos consumidos'), ('recuperados', 'Recuperados (backfill recente)'), ('on_demand', 'Sob demanda (manual)'), ('fn_candidatos', 'Candidatos a falso negativo'), ('shadow_disagree', 'Divergência shadow vs ativa')], max_length=30)),
                ('versao_modelo', models.CharField(max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parametros', models.JSONField(default=dict)),
                ('tamanho_alvo', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField()),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amostras_validacao_criadas', to=settings.AUTH_USER_MODEL)),
                ('processos', models.ManyToManyField(related_name='amostras_validacao', through='tribunals.AmostraProcesso', to='tribunals.process')),
                ('tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amostras_validacao', to='tribunals.tribunal')),
            ],
            options={
                'verbose_name': 'amostra de validação',
                'verbose_name_plural': 'amostras de validação',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='amostraprocesso',
            name='amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tribunals.amostravalidacao'),
        ),
        migrations.CreateModel(
            name='ClassificacaoShadowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_shadow', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('categoria', models.CharField(choices=[('PRECATORIO', 'Precatório'), ('PRE_PRECATORIO', 'Pré-precatório'), ('DIREITO_CREDITORIO', 'Direito creditório'), ('NAO_LEAD', 'Não-lead')], max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_logs', to='tribunals.process')),
            ],
            options={
                'verbose_name': 'log de classificação shadow',
                'verbose_name_plural': 'logs de classificação shadow',
            },
        ),
        migrations.CreateModel(
            name='ProcessoValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_hash', models.CharField(blank=True, max_length=64)),
                ('resultado', models.CharField(choices=[('eh_lead', 'É lead (genérico)'), ('eh_precatorio', 'É precatório (N1)'), ('eh_pre', 'É pré-precatório (N2)'), ('eh_dc', 'É direito creditório (N3)'), ('nao_lead', 'Não é lead'), ('incerto', 'Incerto'), ('precisa_enriquecer', 'Precisa enriquecer'), ('skip', 'Pulou (skip)')], max_length=20)),
                ('confianca', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='alta', max_length=10)),
                ('motivo', models.TextField(blank=True)),
                ('tempo_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('versao_modelo', models.CharField(max_length=10)),
                ('classificacao_no_momento', models.CharField(max_length=20)),
                ('score_no_momento', models.FloatField()),
                ('features_snapshot', models.JSONField(default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('label_final', models.CharField(blank=True, choices=[('eh_lead', 'É lead (genérico)'), ('eh_precatorio', 'É precatório (N1)'), ('eh_pre', 'É pré-precatório (N2)'), ('eh_dc', 'É direito creditório (N3)'), ('nao_lead', 'Não é lead'), ('incerto', 'Incerto'), ('precisa_enriquecer', 'Precisa enriquecer'), ('skip', 'Pulou (skip)')], max_length=20, null=True)),
                ('label_final_resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('amostra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to='tribunals.amostravalidacao')),
                ('label_final_resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='tribunals.process')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validação de processo',
                'verbose_name_plural': 'validações de processo',
                'permissions': [('can_validate_lead', 'Pode anotar validações de leads'), ('can_publish_model', 'Pode promover ClassificadorVersao e editar thresholds'), ('can_view_validacao_dashboard', 'Pode ver dashboard de validação'), ('can_resolve_disagreement', 'Pode resolver divergências preenchendo label_final')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_modelo', models.CharField(max_length=10)),
                ('threshold_precatorio', models.FloatField()),
                ('threshold_pre', models.FloatField()),
                ('threshold_dc', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thresholds_atualizados', to=settings.AUTH_USER_MODEL)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='tribunals.tribunal')),
            ],
            options={
                'verbose_name': 'threshold por tribunal',
                'verbose_name_plural': 'thresholds por tribunal',
            },
        ),
        migrations.AddIndex(
            model_name='amostravalidacao',
            index=models.Index(fields=['-criada_em'], name='tribunals_a_criada__174db1_idx'),
        ),
        migrations.AddIndex(
            model_name='amostravalidacao',
            index=models.Index(fields=['estrategia'], name='tribunals_a_estrate_6c7de0_idx'),
        ),
        migrations.AddIndex(
            model_name='amostraprocesso',
            index=models.Index(fields=['amostra', 'ordem'], name='tribunals_a_amostra_9aaefd_idx'),
        ),
        migrations.AddConstraint(
            model_name='amostraprocesso',
            constraint=models.UniqueConstraint(fields=('amostra', 'processo'), name='uq_amostra_processo'),
        ),
        migrations.AddIndex(
            model_name='classificacaoshadowlog',
            index=models.Index(fields=['versao_shadow', 'criada_em'], name='shadow_log_versao_em_idx'),
        ),
        migrations.AddIndex(
            model_name='processovalidacao',
            index=models.Index(fields=['processo', 'criada_em'], name='tribunals_p_process_fa76cf_idx'),
        ),
        migrations.AddIndex(
            model_name='processovalidacao',
            index=models.Index(fields=['usuario', 'criada_em'], name='tribunals_p_usuario_cf49b9_idx'),
        ),
        migrations.AddIndex(
            model_name='processovalidacao',
            index=models.Index(fields=['resultado'], name='tribunals_p_resulta_519451_idx'),
        ),
        migrations.AddIndex(
            model_name='processovalidacao',
            index=models.Index(fields=['amostra'], name='tribunals_p_amostra_fdd1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='processovalidacao',
            index=models.Index(fields=['label_final'], name='tribunals_p_label_f_fb1d2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='processovalidacao',
            constraint=models.UniqueConstraint(fields=('processo', 'usuario'), name='uq_processo_usuario_validacao'),
        ),
        migrations.AddConstraint(
            model_name='thresholdtribunal',
            constraint=models.UniqueConstraint(fields=('tribunal', 'versao_modelo'), name='uq_threshold_tribunal_versao'),
        ),
        migrations.AddConstraint(
            model_name='thresholdtribunal',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('tribunal', 'versao_modelo'), name='uq_threshold_ativo_por_tribunal_versao'),
        ),
    ]
