# Generated by Django 5.1.4 on 2026-05-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0024_validacao_humana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostravalidacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='amostravalidacao',
            name='criada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_validacao_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
