# Generated by Django 5.1.4 on 2026-05-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0027_can_view_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadconsumption',
            name='lote_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID do lote de reporte (idempotência). NULL = legado.', null=True),
        ),
        migrations.AddConstraint(
            model_name='leadconsumption',
            constraint=models.UniqueConstraint(condition=models.Q(('lote_id__isnull', False)), fields=('cliente', 'processo', 'lote_id'), name='uniq_consumo_cliente_proc_lote'),
        ),
    ]
