# Generated by Django 5.1.4 on 2026-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0046_process_tem_sinal_precatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='datajud_varredura_cursor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='datajud_varredura_docs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='datajud_varredura_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribunal',
            name='datajud_varredura_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
