"""`tribunals_incidente` — a tabela do precatório que o tribunal não numerou.

O QUE ELA GUARDA
----------------
O incidente do e-SAJ. Sonda de 01-02/09/2026 (100 processos do TJSP, sementes
20260901/20260902): **201 de 210 incidentes (95,7%) são `Precatório`/`RPV` e
não têm CNJ nenhum**. Sem número não há porta pelo DJEN nem pelo Datajud —
inventar um CNJ sintético para caber em `tribunals_process` seria fabricar
identificador que não existe no mundo. Racional completo no docstring do model.

POR QUE A MIGRATION É ESCRITA ASSIM (e não um `CreateModel` seco)
------------------------------------------------------------------
`CreateModel` faz duas coisas numa transação só: cria a tabela nova (barata,
sem lock em nada de terceiro) e **adiciona a FK para `tribunals_process`**, que
tem ~104 M linhas. `ADD CONSTRAINT ... FOREIGN KEY` não lê uma linha do pai —
mas pede `SHARE ROW EXCLUSIVE` nele, e todo lock nesta casa **enfileira**: em
25/08/2026 um `ALTER TABLE` preso atrás de uma transação de 88 min levou
produção a 63 sessões esperando `Lock`. Em 02/09 o bloqueador medido eram
SELECTs de agregação de até 1.081 s.

Some-se a isso que o `web` de produção roda `migrate --noinput && gunicorn` no
comando do container: uma migration que estoura por lock **impede o `web` de
subir**. Uma migration de tabela nova não pode virar indisponibilidade.

Daí a mesma receita de três partes da 0057:

  a) **pergunta antes de agir** — se a tabela já existe, não emite DDL nenhuma
     e não pede lock nenhum (custo zero em todo boot posterior ao primeiro);
  b) **a parte cara é separada e tem laço com teto curto** — a tabela e os
     índices nascem SEM a FK (nenhum lock em `tribunals_process`); a FK entra
     depois, em transação própria, com `SET LOCAL lock_timeout` de 3 s e
     `TENTATIVAS` repetições, para chegar na fresta entre as consultas longas;
  c) **falha alto no fim** — esgotadas as tentativas, estoura. Tabela sem a FK
     declarada é exatamente a divergência declarado-vs-banco que a 0056
     inventariou; não se troca um problema visível por um invisível.

`DEFAULT ''` EM TODA COLUNA DE TEXTO
------------------------------------
A tabela é nova e não tem escritor antigo, então o incidente da 0052/0054 não
se aplica a ela hoje. O `DEFAULT` está aqui assim mesmo porque a regra é da
casa e o dia em que ela é lembrada é sempre depois: `grau` (0052) custou 10.410
`IngestionRun` `failed` e 32 publicações num dia; as quatro colunas da 0054
fecharam a terceira porta por dias (255 `EdicaoDiario` em falha). O
`DEFAULT` só é usado por quem NÃO nomeia a coluna — código atual manda o valor
explícito e nada muda para ele. Cobrado por `tests/test_default_no_banco.py`.

`codigo_esaj` também nasce com `DEFAULT ''`, e o que impede a linha órfã
silenciosa não é o banco: é a unique `(processo_id, codigo_esaj)` — um segundo
incidente sem código colidiria alto — mais o escritor, que descarta a ficha sem
código e CONTA o descarte (`enrichers/drainer.py::gravar_incidentes`).
"""
import time

import django.db.models.deletion
from django.db import migrations, models

TABELA = 'tribunals_incidente'
FK = 'tribunals_incidente_processo_id_444aeffa_fk_tribunals'
LOCK_TIMEOUT = '3s'
TENTATIVAS = 40
PAUSA_S = 0.4

#: Idêntico ao que `sqlmigrate` gera, MENOS a FK (que sai no passo seguinte) e
#: MAIS o `DEFAULT` de cada coluna de texto/JSONB.
DDL_TABELA = """
CREATE TABLE IF NOT EXISTS "tribunals_incidente" (
    "id"            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo_esaj"   varchar(32)  NOT NULL DEFAULT '',
    "tipo"          varchar(16)  NOT NULL DEFAULT '',
    "classe"        varchar(120) NOT NULL DEFAULT '',
    "sequencial"    varchar(8)   NOT NULL DEFAULT '',
    "cnj_principal" varchar(25)  NOT NULL DEFAULT '',
    "cnj_proprio"   varchar(25)  NOT NULL DEFAULT '',
    "situacao"      varchar(60)  NOT NULL DEFAULT '',
    "foro"          varchar(255) NOT NULL DEFAULT '',
    "vara"          varchar(255) NOT NULL DEFAULT '',
    "assunto"       varchar(255) NOT NULL DEFAULT '',
    "controle"      varchar(40)  NOT NULL DEFAULT '',
    "recebido_em"   date NULL,
    "valor"         numeric(18, 2) NULL,
    "requerentes"   jsonb NOT NULL DEFAULT '[]'::jsonb,
    "ent_devedoras" jsonb NOT NULL DEFAULT '[]'::jsonb,
    "fonte"         varchar(16) NOT NULL DEFAULT '',
    "coletado_em"   timestamp with time zone NOT NULL DEFAULT now(),
    "atualizado_em" timestamp with time zone NOT NULL DEFAULT now(),
    "processo_id"   bigint NOT NULL,
    CONSTRAINT "uniq_incidente_processo_codigo" UNIQUE ("processo_id", "codigo_esaj")
)
"""

DDL_INDICES = (
    'CREATE INDEX IF NOT EXISTS "tribunals_incidente_processo_id_444aeffa" '
    'ON "tribunals_incidente" ("processo_id")',
    'CREATE INDEX IF NOT EXISTS "incid_tipo_idx" ON "tribunals_incidente" ("tipo")',
    'CREATE INDEX IF NOT EXISTS "incid_cnj_proprio_idx" '
    'ON "tribunals_incidente" ("cnj_proprio")',
    'CREATE INDEX IF NOT EXISTS "incid_coletado_em_idx" '
    'ON "tribunals_incidente" ("coletado_em")',
)

SQL_TEM_FK = """
SELECT 1 FROM pg_constraint c
JOIN pg_class t ON t.oid = c.conrelid
WHERE t.relname = %s AND c.conname = %s AND c.contype = 'f'
"""


def _tem_fk(cursor) -> bool:
    cursor.execute(SQL_TEM_FK, [TABELA, FK])
    return cursor.fetchone() is not None


def criar(apps, schema_editor):
    connection = schema_editor.connection

    # (a) tabela + índices: nada aqui toca `tribunals_process`.
    with connection.cursor() as cursor:
        cursor.execute(DDL_TABELA)
        for ddl in DDL_INDICES:
            cursor.execute(ddl)
        ja_tem = _tem_fk(cursor)
    if ja_tem:
        print(f'0058: {TABELA} e a FK já estão de pé — nenhum lock pedido')
        return

    # (b) a FK, que é a única parte que pede lock em tabela de 104 M linhas.
    ultimo = None
    for tentativa in range(1, TENTATIVAS + 1):
        try:
            with connection.cursor() as cursor:
                cursor.execute('BEGIN')
                cursor.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
                cursor.execute(
                    f'ALTER TABLE "{TABELA}" ADD CONSTRAINT "{FK}" '
                    f'FOREIGN KEY ("processo_id") REFERENCES "tribunals_process" ("id") '
                    f'DEFERRABLE INITIALLY DEFERRED'
                )
                cursor.execute('COMMIT')
            print(f'0058: FK para tribunals_process criada na tentativa {tentativa}')
            return
        except Exception as exc:      # LockNotAvailable, quase sempre
            ultimo = exc
            with connection.cursor() as cursor:
                cursor.execute('ROLLBACK')
            time.sleep(PAUSA_S)

    # (c) falhar alto: tabela sem a FK que o model declara é divergência.
    raise RuntimeError(
        f'0058: não consegui o lock para criar a FK em {TENTATIVAS} tentativas de '
        f'{LOCK_TIMEOUT} (último erro: {ultimo}). NÃO subir o lock_timeout — todo lock enfileira e trava '
        f'quem chega depois. Aplique pelo worker, fora do boot do web: '
        f'docker exec voyager-worker_diarios-1 python manage.py migrate tribunals 0058'
    )


def desfazer(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'DROP TABLE IF EXISTS "{TABELA}"')


class Migration(migrations.Migration):
    # autocommit: o laço precisa de uma transação POR tentativa, e uma
    # transação que já falhou não aceita o próximo statement.
    atomic = False

    dependencies = [
        ('tribunals', '0057_default_no_banco_colunas_novas'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Incidente',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                                   serialize=False, verbose_name='ID')),
                        ('codigo_esaj', models.CharField(blank=True, max_length=32)),
                        ('tipo', models.CharField(blank=True, max_length=16)),
                        ('classe', models.CharField(blank=True, max_length=120)),
                        ('sequencial', models.CharField(blank=True, max_length=8)),
                        ('cnj_principal', models.CharField(blank=True, max_length=25)),
                        ('cnj_proprio', models.CharField(blank=True, max_length=25)),
                        ('situacao', models.CharField(blank=True, max_length=60)),
                        ('foro', models.CharField(blank=True, max_length=255)),
                        ('vara', models.CharField(blank=True, max_length=255)),
                        ('assunto', models.CharField(blank=True, max_length=255)),
                        ('controle', models.CharField(blank=True, max_length=40)),
                        ('recebido_em', models.DateField(blank=True, null=True)),
                        ('valor', models.DecimalField(blank=True, decimal_places=2,
                                                      max_digits=18, null=True)),
                        ('requerentes', models.JSONField(blank=True, default=list)),
                        ('ent_devedoras', models.JSONField(blank=True, default=list)),
                        ('fonte', models.CharField(blank=True, max_length=16)),
                        ('coletado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                        ('processo', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='incidentes', to='tribunals.process')),
                    ],
                    options={
                        'indexes': [
                            models.Index(fields=['tipo'], name='incid_tipo_idx'),
                            models.Index(fields=['cnj_proprio'], name='incid_cnj_proprio_idx'),
                            models.Index(fields=['coletado_em'], name='incid_coletado_em_idx'),
                        ],
                        'constraints': [
                            models.UniqueConstraint(fields=('processo', 'codigo_esaj'),
                                                    name='uniq_incidente_processo_codigo'),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(criar, desfazer),
            ],
        ),
    ]
