"""`tribunals_magistrado` + `tribunals_magistradoatuacao` — quem assinou o ato.

O QUE ELAS GUARDAM
------------------
O nome do magistrado está escrito no corpo das publicações que já ingerimos e
nunca foi lido por nada nesta casa. Medido em 03/09/2026, no índice de
publicações: **5.631.275** documentos do TJSP carregam o marcador
`Magistrado(a)` e **8.472.693** no país. O extrator determinístico é
`tribunals/services/magistrados.py`; o racional da identidade
`(tribunal, órgão, nome)` está no docstring do model `Magistrado`.

POR QUE A MIGRATION NÃO É UM `CreateModel` SECO
-----------------------------------------------
Mesma receita da 0058, pelo mesmo motivo medido: `CreateModel` cria a tabela
**e** adiciona as FKs na mesma transação, e `ADD CONSTRAINT ... FOREIGN KEY`
pede `SHARE ROW EXCLUSIVE` na tabela REFERENCIADA. Aqui a referenciada é
`tribunals_process`, com ~104 milhões de linhas e sob escrita contínua. Nesta
casa todo lock **enfileira**: em 25/08/2026 um `ALTER TABLE` preso levou
produção a 63 sessões esperando `Lock`, e em 02/09 o bloqueador medido eram
SELECTs de agregação de **616 s a 1.081 s**. O R-esaj só conseguiu esse lock na
11ª tentativa.

E o `web` de produção roda `migrate --noinput && gunicorn` no comando do
container: migration que estoura por lock **impede o `web` de subir** — foi o
crash-loop de 19 restarts de 02/09. Daí as três partes:

  a) **pergunta antes de agir** — tabelas e FKs já de pé ⇒ nenhuma DDL, nenhum
     lock pedido (custo zero em todo boot posterior ao primeiro);
  b) **a parte cara é separada e tem laço com teto CURTO** — as duas tabelas e
     todos os índices nascem sem FK nenhuma; as FKs entram depois, uma
     transação por tentativa, `SET LOCAL lock_timeout = '3s'`. **Não se sobe o
     teto**: subir o teto é comprar o auto-jam;
  c) **falha alto no fim**, com o comando manual na mensagem. Tabela sem a FK
     que o model declara é exatamente a divergência declarado-vs-banco que a
     0056 inventariou.

POR QUE NÃO EXISTE FK PARA `tribunals_movimentacao`
---------------------------------------------------
`movimentacao_id` é `bigint` puro, deliberadamente. A tabela referenciada teria
**1,4 bilhão de linhas** e recebe INSERT 24 h por dia — pedir
`SHARE ROW EXCLUSIVE` nela é o auto-jam de 25/08 marcado para acontecer. A FK
não compraria nada que a unique `(magistrado_id, movimentacao_id)` já não dê:
o escritor sempre parte de uma `Movimentacao` que acabou de ler.

`DEFAULT ''` EM TODA COLUNA DE TEXTO
------------------------------------
As tabelas são novas e não têm escritor antigo, então o incidente da 0052/0054
não se aplica a elas hoje. O `DEFAULT` está aqui assim mesmo porque a regra é
da casa e o dia em que ela é lembrada é sempre DEPOIS: `grau` (0052) custou
10.410 `IngestionRun` `failed` e 32 publicações num dia; as quatro colunas da
0054 fecharam a terceira porta por dias. O `DEFAULT` só é usado por quem NÃO
nomeia a coluna. Cobrado por `tests/test_default_no_banco.py`.

`n_publicacoes` NASCE `NULL` E ISSO É O PONTO
---------------------------------------------
`NULL` = não contamos; `0` = contamos e deu zero. Mesma convenção de
`voyager-entidades.n_processos` (`SEARCH_SCHEMA.md`, decisão 8), pela mesma
razão: um contador `NOT NULL DEFAULT 0` faria toda linha nunca medida dizer
"este magistrado não tem publicação", que é uma afirmação que ninguém fez.

AS TABELAS NASCEM VAZIAS, DE PROPÓSITO
--------------------------------------
Esta migration NÃO faz backfill. Medido em 03/09/2026, em duas amostras
independentes — 42.281 publicações no Postgres com salto pseudoaleatório
(11,39%) e 600 sorteadas no ES (11,83%) —, a fração de publicações que produz
atribuição projeta **~184 a 191 milhões de linhas** em
`tribunals_magistradoatuacao` sobre as 1.618.133.888 de
`tribunals_movimentacao`. Num banco que já é I/O-bound, encher isso é decisão
de quem opera o disco, com faixa fechada de pk, e não efeito colateral de um
`git pull`.
"""
import time

import django.db.models.deletion
from django.db import migrations, models

LOCK_TIMEOUT = '3s'
TENTATIVAS = 40
PAUSA_S = 0.4

T_MAG = 'tribunals_magistrado'
T_ATU = 'tribunals_magistradoatuacao'

#: Idêntico ao que `sqlmigrate` geraria, MENOS as FKs (passo seguinte) e MAIS
#: o `DEFAULT` de cada coluna de texto.
DDL_TABELAS = (
    """
    CREATE TABLE IF NOT EXISTS "tribunals_magistrado" (
        "id"               bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "nome"             varchar(255) NOT NULL DEFAULT '',
        "nome_chave"       varchar(255) NOT NULL DEFAULT '',
        "orgao"            varchar(255) NOT NULL DEFAULT '',
        "orgao_chave"      varchar(255) NOT NULL DEFAULT '',
        "cargo"            varchar(120) NOT NULL DEFAULT '',
        "formato"          varchar(32)  NOT NULL DEFAULT '',
        "fonte"            varchar(24)  NOT NULL DEFAULT '',
        "n_publicacoes"    integer NULL,
        "n_publicacoes_em" timestamp with time zone NULL,
        "primeira_em"      date NULL,
        "ultima_em"        date NULL,
        "criado_em"        timestamp with time zone NOT NULL DEFAULT now(),
        "atualizado_em"    timestamp with time zone NOT NULL DEFAULT now(),
        "tribunal_id"      varchar(10) NOT NULL,
        CONSTRAINT "uniq_magistrado_tribunal_orgao_nome"
            UNIQUE ("tribunal_id", "orgao_chave", "nome_chave")
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS "tribunals_magistradoatuacao" (
        "id"              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "movimentacao_id" bigint NOT NULL,
        "formato"         varchar(32)  NOT NULL DEFAULT '',
        "cargo"           varchar(120) NOT NULL DEFAULT '',
        "publicado_em"    date NULL,
        "criado_em"       timestamp with time zone NOT NULL DEFAULT now(),
        "magistrado_id"   bigint NOT NULL,
        "processo_id"     bigint NOT NULL,
        CONSTRAINT "uniq_atuacao_magistrado_mov"
            UNIQUE ("magistrado_id", "movimentacao_id")
    )
    """,
)

DDL_INDICES = (
    'CREATE INDEX IF NOT EXISTS "tribunals_magistrado_tribunal_id_idx" '
    'ON "tribunals_magistrado" ("tribunal_id")',
    'CREATE INDEX IF NOT EXISTS "mag_trib_nome_idx" '
    'ON "tribunals_magistrado" ("tribunal_id", "nome_chave")',
    'CREATE INDEX IF NOT EXISTS "mag_nome_idx" '
    'ON "tribunals_magistrado" ("nome_chave")',
    'CREATE INDEX IF NOT EXISTS "tribunals_magistradoatuacao_magistrado_id_idx" '
    'ON "tribunals_magistradoatuacao" ("magistrado_id")',
    'CREATE INDEX IF NOT EXISTS "atu_mag_data_idx" '
    'ON "tribunals_magistradoatuacao" ("magistrado_id", "publicado_em" DESC)',
    'CREATE INDEX IF NOT EXISTS "atu_processo_idx" '
    'ON "tribunals_magistradoatuacao" ("processo_id")',
)

#: (tabela, constraint, coluna, tabela referenciada, COLUNA referenciada).
#: A coluna referenciada é explícita porque `tribunals_tribunal` **não tem
#: `id`**: a PK dele é `sigla` (varchar). Escrever `REFERENCES … ("id")` por
#: hábito falha com `column "id" ... does not exist` — e falhava DENTRO do laço
#: de lock, gastando 40 tentativas num erro que nenhuma espera conserta.
FKS = (
    (T_MAG, 'tribunals_magistrado_tribunal_id_fk', 'tribunal_id',
     'tribunals_tribunal', 'sigla'),
    (T_ATU, 'tribunals_magistradoatuacao_magistrado_id_fk', 'magistrado_id',
     T_MAG, 'id'),
    (T_ATU, 'tribunals_magistradoatuacao_processo_id_fk', 'processo_id',
     'tribunals_process', 'id'),
)

#: `lock_not_available`. É o ÚNICO erro que esperar conserta.
SQLSTATE_LOCK = '55P03'


def _e_lock(exc) -> bool:
    """O erro é disputa de lock, ou é defeito da DDL?

    O laço existe para chegar na fresta entre as consultas longas de produção;
    repetir 40 vezes um `column "id" does not exist` não é resiliência, é
    esconder o defeito atrás de 16 s de espera e de uma mensagem que culpa o
    lock. Qualquer outro SQLSTATE sobe na hora, com o erro original."""
    for candidato in (exc, getattr(exc, '__cause__', None)):
        estado = (getattr(candidato, 'sqlstate', None)
                  or getattr(candidato, 'pgcode', None))
        if estado == SQLSTATE_LOCK:
            return True
    return 'lock timeout' in str(exc).lower()

SQL_TEM_FK = """
SELECT 1 FROM pg_constraint c
JOIN pg_class t ON t.oid = c.conrelid
WHERE t.relname = %s AND c.conname = %s AND c.contype = 'f'
"""


def _tem_fk(cursor, tabela, nome) -> bool:
    cursor.execute(SQL_TEM_FK, [tabela, nome])
    return cursor.fetchone() is not None


def _criar_fk(connection, tabela, nome, coluna, referenciada, col_ref):
    """Uma FK, em laço, com teto curto. Transação POR tentativa."""
    with connection.cursor() as cursor:
        if _tem_fk(cursor, tabela, nome):
            print(f'0059: {nome} já existe — nenhum lock pedido')
            return

    ultimo = None
    for tentativa in range(1, TENTATIVAS + 1):
        try:
            with connection.cursor() as cursor:
                cursor.execute('BEGIN')
                cursor.execute(f"SET LOCAL lock_timeout = '{LOCK_TIMEOUT}'")
                cursor.execute(
                    f'ALTER TABLE "{tabela}" ADD CONSTRAINT "{nome}" '
                    f'FOREIGN KEY ("{coluna}") REFERENCES "{referenciada}" ("{col_ref}") '
                    f'DEFERRABLE INITIALLY DEFERRED'
                )
                cursor.execute('COMMIT')
            print(f'0059: {nome} → {referenciada} criada na tentativa {tentativa}')
            return
        except Exception as exc:
            with connection.cursor() as cursor:
                cursor.execute('ROLLBACK')
            if not _e_lock(exc):
                raise RuntimeError(
                    f'0059: {nome} falhou por algo que ESPERAR não conserta '
                    f'({exc}). Corrija a DDL — o laço é para disputa de lock, '
                    f'não para defeito de schema.') from exc
            ultimo = exc
            time.sleep(PAUSA_S)

    raise RuntimeError(
        f'0059: não consegui o lock para criar {nome} em {referenciada} em '
        f'{TENTATIVAS} tentativas de {LOCK_TIMEOUT} (último erro: {ultimo}). '
        f'NÃO subir o lock_timeout — todo lock enfileira e trava quem chega '
        f'depois. Aplique pelo worker, fora do boot do web: '
        f'docker exec voyager-worker_diarios-1 python manage.py migrate tribunals 0059'
    )


def criar(apps, schema_editor):
    connection = schema_editor.connection

    # (a) tabelas + índices: nada aqui toca `tribunals_process`.
    with connection.cursor() as cursor:
        for ddl in DDL_TABELAS:
            cursor.execute(ddl)
        for ddl in DDL_INDICES:
            cursor.execute(ddl)

    # (b) as FKs, a única parte que pede lock em tabela de 104 M linhas.
    for tabela, nome, coluna, referenciada, col_ref in FKS:
        _criar_fk(connection, tabela, nome, coluna, referenciada, col_ref)


def desfazer(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'DROP TABLE IF EXISTS "{T_ATU}"')
        cursor.execute(f'DROP TABLE IF EXISTS "{T_MAG}"')


class Migration(migrations.Migration):
    # autocommit: o laço precisa de uma transação POR tentativa, e uma
    # transação que já falhou não aceita o próximo statement.
    atomic = False

    dependencies = [
        ('tribunals', '0058_incidente_esaj'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Magistrado',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                                   serialize=False, verbose_name='ID')),
                        ('nome', models.CharField(blank=True, max_length=255)),
                        ('nome_chave', models.CharField(blank=True, max_length=255)),
                        ('orgao', models.CharField(blank=True, max_length=255)),
                        ('orgao_chave', models.CharField(blank=True, max_length=255)),
                        ('cargo', models.CharField(blank=True, max_length=120)),
                        ('formato', models.CharField(blank=True, max_length=32)),
                        ('fonte', models.CharField(blank=True, max_length=24)),
                        ('n_publicacoes', models.IntegerField(blank=True, null=True)),
                        ('n_publicacoes_em', models.DateTimeField(blank=True, null=True)),
                        ('primeira_em', models.DateField(blank=True, null=True)),
                        ('ultima_em', models.DateField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('atualizado_em', models.DateTimeField(auto_now=True)),
                        ('tribunal', models.ForeignKey(
                            on_delete=django.db.models.deletion.PROTECT,
                            related_name='magistrados', to='tribunals.tribunal')),
                    ],
                    options={
                        'indexes': [
                            models.Index(fields=['tribunal', 'nome_chave'],
                                         name='mag_trib_nome_idx'),
                            models.Index(fields=['nome_chave'], name='mag_nome_idx'),
                        ],
                        'constraints': [
                            models.UniqueConstraint(
                                fields=('tribunal', 'orgao_chave', 'nome_chave'),
                                name='uniq_magistrado_tribunal_orgao_nome'),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name='MagistradoAtuacao',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                                   serialize=False, verbose_name='ID')),
                        ('movimentacao_id', models.BigIntegerField()),
                        ('formato', models.CharField(blank=True, max_length=32)),
                        ('cargo', models.CharField(blank=True, max_length=120)),
                        ('publicado_em', models.DateField(blank=True, null=True)),
                        ('criado_em', models.DateTimeField(auto_now_add=True)),
                        ('magistrado', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='atuacoes', to='tribunals.magistrado')),
                        ('processo', models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='magistrados', to='tribunals.process')),
                    ],
                    options={
                        'indexes': [
                            models.Index(fields=['magistrado', '-publicado_em'],
                                         name='atu_mag_data_idx'),
                            models.Index(fields=['processo'], name='atu_processo_idx'),
                        ],
                        'constraints': [
                            models.UniqueConstraint(
                                fields=('magistrado', 'movimentacao_id'),
                                name='uniq_atuacao_magistrado_mov'),
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(criar, desfazer),
            ],
        ),
    ]
